#%%
# Pty-Chi (LSQML) reconstruction of the 12-ID-C Siemens star scan.
# Port of fracPy_Argonne/Argonne_work/reconstruction_20260726_seimenStar.py
#
# fracPy runs a chain of engines with hand-tuned betas (mPIE -> multiPIE -> pcPIE).
# LSQML solves the object/probe step sizes analytically, so instead of beta staging
# the schedule below is expressed with per-parameter OptimizationPlan(start=...):
#
#   epoch 0        object only                      (fracPy: mPIE, betaProbe ~ 0)
#   probe_start    probe modes released             (fracPy: multiPIE)
#   opr_start      OPR modes + intensity variation
#   position_start position correction on           (fracPy: pcPIE)
#
# fracPy -> Pty-Chi parameter map:
#   exampleData.ptychogram         -> data_options.data                (n, N, N) intensities
#   exampleData.encoder / dxo      -> probe_position_{y,x}_px
#   exampleData.wavelength         -> data_options.wavelength_m
#   exampleData.dxo / dxp          -> object_options.pixel_size_m
#   propagatorType 'Fraunhofer'    -> free_space_propagation_distance_m = inf
#   reconstruction.npsm            -> probe axis 1 (incoherent modes)
#   params.orthogonalizationSwitch -> probe_options.orthogonalize_incoherent_modes
#   params.momentumAcceleration    -> reconstructor_options.momentum_acceleration_gain
#   params.positionCorrectionSwitch-> probe_position_options.optimizable

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "5"  # This makes GPU N appear as GPU 0 to CuPy

import json
import logging
from pathlib import Path

import h5py
import numpy as np
import tifffile
import torch
import matplotlib.pyplot as plt

import ptychi.api as api
from ptychi.api.options.base import OptimizationPlan
from ptychi.api.task import PtychographyTask
from ptychi.utils import (
    add_additional_opr_probe_modes_to_probe,
    generate_initial_opr_mode_weights,
    get_default_complex_dtype,
    get_suggested_object_size,
    orthogonalize_initial_probe,
    rescale_probe,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")


#%% ---------------------------------------------------------------- paths

scan = "fly520"
scan_initialGuess = "fly520"  # scan used to generate the initial guess (positions + probe)
data_root = Path("/mnt/micdata2/4IDD/2026_Sep/results/ML_recon")

dp_file = data_root / scan / "data_roi0_Ndp256_us1_dp.hdf5"
para_file = data_root / scan / "data_roi0_Ndp256_us1_para.hdf5"

# Previous Pty-Chi recon used as the source of positions and of the probe guess
# (same file the fracPy script read). Set to None to start from the para file
# positions and a synthesized probe instead.
init_recon_file = (
    Path("/mnt/micdata2/4IDD/2026_Sep/ptychi_recons/batch_JD/S0200")
    / "Ndp128_LSQML_c500_m0.5_gaussian_p10_cp_pc500_f_ul2" / "recon_Niter2000.h5"
)

# Results are written as <recon_parent_dir>/<scan>/<auto-generated name>/, the same
# layout PEAR (pear.ptycho_recon, used by the beamline batch script) produces:
#   ptychi_recons/S0019/Ndp1024_LSQML_c20_m0.5_gaussian_p10_cp_mm_opr3_ic_pc1_f_ul2/
#       pear_params.json  dp_sum.tiff  init_positions.png  init_probe_mag.tiff
#       recon_Niter200.h5  recon_Niter400.h5  ...
#       loss/  object_mag/  object_ph/  positions/  probe_mag/
# The folder name is built by make_recon_dir_name() from the knobs below.
recon_parent_dir = Path("/mnt/micdata2/4IDD/2026_Sep/ptychi_recons")
recon_dir_suffix = ""            # appended to the folder name, e.g. "_v2" or "_pos"

# Set True to skip the beamline files and run the whole pipeline on synthetic
# data (useful to debug the structure without the data share).
use_simulated_data = False


#%% ---------------------------------------------------------------- geometry & knobs

n_dp = 256                       # detector crop, fracPy cropSize
wavelength_m = 1.997e-10          # fracPy exampleData.wavelength
det_pixel_m = 7.5e-05             # fracPy exampleData.dxd
det_dist_m = 1.9                # fracPy exampleData.zo
far_field = True                 # fracPy propagatorType 'Fraunhofer'

# fracPy fixed dxo = dxp = 1.76e-8; that is exactly the far-field sampling below.
pixel_size_m = wavelength_m * det_dist_m / (n_dp * det_pixel_m)
# pixel_size_m = 3.97e-8

n_probe_modes = 10                # fracPy reconstruction.npsm
n_opr_modes = 1                  # variable probe (OPR); 1 disables it
probe_diameter_m = 1.0e-6        # only used when no probe comes from init_recon_file
object_padding_px = 100          # extra object buffer around the scan bounding box

num_epochs = 2000
save_freq_iterations = 500       # write a recon_Niter*.h5 snapshot every N epochs
batch_size = 250                 # the number of scan positions
batching_mode = api.BatchingModes.COMPACT
noise_model = api.NoiseModels.GAUSSIAN
momentum_gain = 0.25              # fracPy params.momentumAcceleration

probe_start = 200                  # epoch at which the probe starts updating
opr_start = 200                   # None disables OPR weight optimization
position_start = 2000              # None disables position correction (fracPy pcPIE)
orthogonalization_stride = 5    # fracPy params.orthogonalizationFrequency
position_update_limit_px = 20.0
optimize_intensity_variation = False   # per-position beam intensity ("ic")
center_probe = False                   # fracPy comStabilizationSwitch ("cp")
update_object_with_higher_probe_modes = True   # ("mm")

# fracPy flip switches
flip_dp_x = False
flip_dp_y = False
flip_positions_x = False
flip_positions_y = False
swap_position_axes = False       # True if stored positions are (x, y) not (y, x)

device = api.Devices.GPU if torch.cuda.is_available() else api.Devices.CPU
dtype = api.Dtypes.FLOAT32
random_seed = 123

print(f"pixel size = {pixel_size_m * 1e9:.3f} nm, FOV = {n_dp * pixel_size_m * 1e6:.2f} um")


#%% ---------------------------------------------------------------- helpers


def center_crop_or_pad(arr, size):
    """Center-crop (or zero-pad) the last two axes of `arr` to (size, size)."""
    out = arr
    for axis in (-2, -1):
        n = out.shape[axis]
        if n > size:
            start = (n - size) // 2
            out = np.take(out, np.arange(start, start + size), axis=axis)
        elif n < size:
            pad = [(0, 0)] * out.ndim
            before = (size - n) // 2
            pad[axis] = (before, size - n - before)
            out = np.pad(out, pad)
    return out


def make_disk_probe(size, diameter_px):
    """Soft-edged disk, used when there is no probe to inherit."""
    yy, xx = np.mgrid[:size, :size] - (size - 1) / 2
    r = np.hypot(yy, xx)
    edge = max(0.1 * diameter_px / 2, 1.0)
    disk = 0.5 * (1 - np.tanh((r - diameter_px / 2) / edge))
    return disk.astype(np.complex64)[None, None]  # (n_opr, n_modes, h, w)


def siemens_star(shape, n_spokes=24):
    yy, xx = np.mgrid[: shape[0], : shape[1]]
    theta = np.arctan2(yy - shape[0] / 2, xx - shape[1] / 2)
    r = np.hypot(yy - shape[0] / 2, xx - shape[1] / 2)
    spokes = (np.cos(n_spokes * theta) > 0) & (r < 0.45 * min(shape))
    return ((1 - 0.15 * spokes) * np.exp(1j * 0.8 * spokes)).astype(np.complex64)


#%% ------------------------------------------------- output in the PEAR/beamline layout


def make_recon_dir_name(suffix=""):
    """Folder name in the beamline convention, e.g.

        Ndp1024_LSQML_c20_m0.5_gaussian_p10_cp_mm_opr3_ic_pc1_f_ul2

    Ndp<detector crop>, batch selection scheme + batch size, m<momentum>,
    noise model, p<probe modes>, cp = probe centering, mm = object updated with
    the higher probe modes, opr<n>, ic = intensity correction, pc0/pc1 =
    position correction, gradient method initial, ul<update limit>.
    """
    batch_tag = {"compact": "c", "random": "r", "uniform": "u"}[batching_mode.value]
    parts = [
        f"Ndp{n_dp}",
        "LSQML",
        f"{batch_tag}{batch_size}",
        f"m{momentum_gain}",
        noise_model.value,
        f"p{n_probe_modes}",
    ]
    if center_probe:
        parts.append("cp")
    if update_object_with_higher_probe_modes:
        parts.append("mm")
    parts.append(f"opr{n_opr_modes}")
    if optimize_intensity_variation:
        parts.append("ic")
    if position_start is None:
        parts.append("pc0")
    else:
        parts += ["pc1", "f", f"ul{position_update_limit_px:g}"]
    return "_".join(parts) + suffix


def _rgb_uint8(arr, cmap="gray", log=False):
    """Colormapped preview, the format PEAR writes its *.tiff previews in."""
    a = np.asarray(arr, dtype=np.float64)
    if log:
        a = np.log10(a - a.min() + 1.0)
    a = (a - a.min()) / max(np.ptp(a), 1e-12)
    return (plt.get_cmap(cmap)(a)[..., :3] * 255).astype(np.uint8)


def _gray_uint16(arr):
    """Min-max scaled 16-bit preview (PEAR's object_mag / object_ph tiffs)."""
    a = np.asarray(arr, dtype=np.float64)
    return ((a - a.min()) / max(np.ptp(a), 1e-12) * 65535).astype(np.uint16)


def collect_params():
    """The knob dump written to pear_params.json, keyed like PEAR's params."""
    return {
        "data_directory": str(data_root),
        "path_to_init_probe": str(init_recon_file) if init_recon_file else "",
        "path_to_init_object": "",
        "path_to_init_positions": str(init_recon_file) if init_recon_file else "",
        "scan_num": scan,
        "instrument": "4idd",
        "det_sample_dist_m": det_dist_m,
        "diff_pattern_size_pix": n_dp,
        "load_processed_hdf5": not use_simulated_data,
        "path_to_processed_hdf5_dp": str(dp_file),
        "path_to_processed_hdf5_pos": str(para_file),
        "position_correction": position_start is not None,
        "position_correction_update_limit": position_update_limit_px,
        "position_correction_gradient_method": "fourier",
        "position_correction_affine_constraint": False,
        "intensity_correction": optimize_intensity_variation,
        "center_probe": center_probe,
        "number_probe_modes": n_probe_modes,
        "update_object_w_higher_probe_modes": update_object_with_higher_probe_modes,
        "number_opr_modes": n_opr_modes,
        "update_batch_size": batch_size,
        "batch_selection_scheme": batching_mode.value,
        "momentum_acceleration": momentum_gain > 0,
        "number_of_slices": 1,
        "number_of_iterations": num_epochs,
        "save_freq_iterations": save_freq_iterations,
        "noise_model": noise_model.value,
        "det_pixel_size_m": det_pixel_m,
        "wavelength_m": wavelength_m,
        "obj_pixel_size_m": pixel_size_m,
        "probe_start_epoch": probe_start,
        "opr_start_epoch": opr_start,
        "position_start_epoch": position_start,
    }


def save_initial_conditions(recon_dir):
    """Write pear_params.json and the dp_sum / init_probe / init_positions previews."""
    recon_dir.mkdir(parents=True, exist_ok=True)

    with open(recon_dir / "pear_params.json", "w") as f:
        json.dump(collect_params(), f, indent=4)

    tifffile.imwrite(recon_dir / "dp_sum.tiff", _rgb_uint8(patterns.sum(0), log=True))

    probe_montage = np.concatenate(
        [np.abs(probe[0, i].numpy()) for i in range(probe.shape[1])], axis=1
    )
    tifffile.imwrite(recon_dir / "init_probe_mag.tiff", _rgb_uint8(probe_montage))

    fig, ax = plt.subplots(figsize=(4, 4))
    ax.plot(positions_px[:, 1], positions_px[:, 0], ".-", lw=0.3, ms=2)
    ax.set_aspect("equal")
    ax.set_title("initial positions [px]")
    fig.savefig(recon_dir / "init_positions.png", dpi=120, bbox_inches="tight")
    plt.close(fig)

    print(f"Reconstruction results will be saved in: {recon_dir}")


# Affine components of the position correction, keyed by iteration; the beamline
# files carry one entry per saved iteration, so this accumulates over the run.
affine_history = {}


def save_reconstruction(task, recon_dir, n_iter=None):
    """Write recon_Niter{n_iter}.h5 plus previews, matching the beamline files.

    `n_iter` defaults to the number of epochs the task has actually run, so this
    can be called straight after a hand-issued task.run(n) without tracking the
    count yourself.

    Datasets (identical names, shapes and dtypes to PEAR's recon_Niter*.h5, so
    these results can be fed straight back in through `init_recon_file`):

        init_positions_px  (n, 2)                float64
        loss               (n_epochs,)           float64
        obj_pixel_size_m   scalar                float64
        object             (n_slices, h, w)      complex64
        opr_mode_weights   (n, n_opr)            float32
        positions_px       (n, 2)                float32
        pos_corr/affine_matrix                   (2, 3) float32
        pos_corr/{scale,asymmetry,rotation,shear}  (n_saves,) float32
        pos_corr/iterations                      (n_saves,) int64
    """
    recon_dir.mkdir(parents=True, exist_ok=True)

    recon_obj = task.get_data_to_cpu("object", as_numpy=True)
    recon_probe = task.get_data_to_cpu("probe", as_numpy=True)
    recon_pos = task.get_data_to_cpu("probe_positions", as_numpy=True)
    weights = task.get_data_to_cpu("opr_mode_weights", as_numpy=True)
    init_pos = task.probe_positions.initial_positions.detach().cpu().numpy()
    loss = task.reconstructor.loss_tracker.table["loss"].to_numpy()
    if n_iter is None:
        n_iter = len(loss)

    comps = task.probe_positions.affine_transform_components
    affine_history[n_iter] = {k: float(np.asarray(comps[k])) for k in comps}
    iters = sorted(affine_history)
    affine_matrix = task.probe_positions.affine_transform_matrix.detach().cpu().numpy()

    with h5py.File(recon_dir / f"recon_Niter{n_iter}.h5", "w") as f:
        f.create_dataset("object", data=recon_obj.astype(np.complex64))
        f.create_dataset("probe", data=recon_probe.astype(np.complex64))
        f.create_dataset("positions_px", data=recon_pos.astype(np.float32))
        f.create_dataset("init_positions_px", data=init_pos.astype(np.float64))
        f.create_dataset("opr_mode_weights", data=weights.astype(np.float32))
        f.create_dataset("loss", data=loss.astype(np.float64))
        f.create_dataset("obj_pixel_size_m", data=np.float64(pixel_size_m))
        g = f.create_group("pos_corr")
        g.create_dataset("affine_matrix", data=affine_matrix.astype(np.float32))
        g.create_dataset("iterations", data=np.asarray(iters, dtype=np.int64))
        for key in ("scale", "asymmetry", "rotation", "shear"):
            g.create_dataset(
                key, data=np.asarray([affine_history[i][key] for i in iters], dtype=np.float32)
            )

    # Previews, one file per saved iteration in its own subfolder.
    roi = task.object.roi_bbox.get_slicer()
    obj_roi = recon_obj[0][roi]
    for sub, img in (
        ("object_mag", _gray_uint16(np.abs(obj_roi))),
        ("object_ph", _gray_uint16(np.angle(obj_roi))),
        (
            "probe_mag",
            _rgb_uint8(
                np.concatenate(
                    [np.abs(recon_probe[0, i]) for i in range(recon_probe.shape[1])], axis=1
                )
            ),
        ),
    ):
        (recon_dir / sub).mkdir(exist_ok=True)
        tifffile.imwrite(recon_dir / sub / f"{sub}_Niter{n_iter}.tiff", img)

    (recon_dir / "loss").mkdir(exist_ok=True)
    fig, ax = plt.subplots(figsize=(5, 3))
    ax.semilogy(np.arange(1, len(loss) + 1), loss)
    ax.set_xlabel("epoch"), ax.set_ylabel("loss")
    fig.savefig(recon_dir / "loss" / f"loss_Niter{n_iter}.png", dpi=120, bbox_inches="tight")
    plt.close(fig)

    (recon_dir / "positions").mkdir(exist_ok=True)
    fig, ax = plt.subplots(figsize=(4, 4))
    ax.plot(init_pos[:, 1], init_pos[:, 0], ".", ms=3, label="initial")
    ax.plot(recon_pos[:, 1], recon_pos[:, 0], ".", ms=3, label="corrected")
    ax.set_aspect("equal"), ax.legend()
    fig.savefig(recon_dir / "positions" / f"positions_Niter{n_iter}.png", dpi=120,
                bbox_inches="tight")
    plt.close(fig)

    print(f"saved {recon_dir / f'recon_Niter{n_iter}.h5'}")


# Where this run's results go. Defined here rather than in the run cell so the save
# cell at the bottom still works when the cells are executed out of order.
recon_dir = recon_parent_dir / scan / make_recon_dir_name(recon_dir_suffix)


#%% ---------------------------------------------------------------- load diffraction patterns

if use_simulated_data:
    # Small synthetic far-field dataset: 8x8 jittered grid over a Siemens star.
    n_dp = 64
    pixel_size_m = wavelength_m * det_dist_m / (n_dp * det_pixel_m)
    n_probe_modes, n_opr_modes, batch_size, object_padding_px = 2, 2, 16, 8

    rng = np.random.default_rng(0)
    grid = (np.arange(8) - 3.5) * 12.0
    gy, gx = np.meshgrid(grid, grid, indexing="ij")
    positions_px = np.stack([gy.ravel(), gx.ravel()], -1) + rng.normal(0, 0.5, (64, 2))

    sim_shape = get_suggested_object_size(positions_px, (n_dp, n_dp), extra=object_padding_px)
    sim_obj = siemens_star(sim_shape)
    sim_probe = make_disk_probe(n_dp, 40)[0, 0]

    patterns = np.empty((len(positions_px), n_dp, n_dp), dtype=np.float32)
    for i, (py, px) in enumerate(positions_px):
        y0 = int(round(sim_shape[0] / 2 + py - n_dp / 2))
        x0 = int(round(sim_shape[1] / 2 + px - n_dp / 2))
        psi = sim_obj[y0 : y0 + n_dp, x0 : x0 + n_dp] * sim_probe
        patterns[i] = np.abs(np.fft.fftshift(np.fft.fft2(psi, norm="ortho"))) ** 2
    patterns = rng.poisson(patterns / patterns.max() * 1e4).astype(np.float32)
    prior = {}
else:
    with h5py.File(dp_file, "r") as f:
        print(f"keys in {dp_file.name}: {list(f.keys())}")
        patterns = f["dp"][()]
    print(f"raw ptychogram: {patterns.shape}")

    patterns = center_crop_or_pad(patterns, n_dp)
    if flip_dp_x:
        patterns = patterns[..., :, ::-1]
    if flip_dp_y:
        patterns = patterns[..., ::-1, :]
    patterns = np.ascontiguousarray(patterns, dtype=np.float32)
    np.clip(patterns, 0, None, out=patterns)

print(f"ptychogram: {patterns.shape}, total counts {patterns.sum():.3e}")


#%% ---------------------------------------------------------------- positions + prior probe/object

if not use_simulated_data:
    prior = {}
    if init_recon_file is not None:
        with h5py.File(init_recon_file, "r") as f:
            print(f"keys in {init_recon_file.name}: {list(f.keys())}")
            # Only the probe is inherited. The object is read for the optional
            # paste-in block further down (off by default); the positions are not
            # read at all -- they always come from the para file below.
            prior["object"] = np.asarray(f["object"][()]).view(np.complex64)
            prior["probe"] = np.asarray(f["probe"][()]).view(np.complex64)

    if "positions_px" in prior:
        positions_px = prior["positions_px"].copy()
    else:
        # fracPy read ppX/ppY (meters) from the para file; Pty-Chi wants pixels.
        with h5py.File(para_file, "r") as f:
            print(f"keys in {para_file.name}: {list(f.keys())}")
            ppx = np.asarray(f["ppX"][()], dtype=np.float64).squeeze()
            ppy = np.asarray(f["ppY"][()], dtype=np.float64).squeeze()
        positions_px = np.stack((ppy, ppx), axis=-1) / pixel_size_m

    if swap_position_axes:
        positions_px = positions_px[:, ::-1].copy()
    if flip_positions_y:
        positions_px[:, 0] = -positions_px[:, 0]
    if flip_positions_x:
        positions_px[:, 1] = -positions_px[:, 1]

# Pty-Chi maps position (0, 0) to the center of the object buffer
# (object_options.determine_position_origin_coords_by), so keep the scan centered.
positions_px = positions_px - positions_px.mean(axis=0, keepdims=True)

assert len(positions_px) == len(patterns), (
    f"{len(patterns)} patterns vs {len(positions_px)} positions"
)
print(
    f"{len(positions_px)} positions: "
    f"y [{positions_px[:, 0].min():.1f}, {positions_px[:, 0].max():.1f}] px, "
    f"x [{positions_px[:, 1].min():.1f}, {positions_px[:, 1].max():.1f}] px"
)

plt.figure(figsize=(4, 4))
plt.plot(positions_px[:, 1], positions_px[:, 0], ".-", lw=0.3, ms=2)
plt.gca().set_aspect("equal")
plt.title("scan positions [px]")
plt.show()


#%% ---------------------------------------------------------------- initial probe

if "probe" in prior:
    probe = center_crop_or_pad(prior["probe"], n_dp)
    # Pty-Chi wants exactly (n_opr, n_modes, h, w); fold any extra leading axes
    # (e.g. a wavelength axis) into the OPR axis.
    probe = probe.reshape((-1,) + probe.shape[-3:])
    probe = torch.as_tensor(np.ascontiguousarray(probe), dtype=get_default_complex_dtype())
    print(f"probe from {init_recon_file.name}: {tuple(probe.shape)}")
else:
    probe = torch.as_tensor(
        make_disk_probe(n_dp, probe_diameter_m / pixel_size_m),
        dtype=get_default_complex_dtype(),
    )
    print(f"synthesized disk probe, diameter {probe_diameter_m * 1e6:.2f} um")

# Incoherent modes: keep what we have, fill the rest with Hermite modes.
if probe.shape[1] > n_probe_modes:
    probe = probe[:, :n_probe_modes]
elif probe.shape[1] < n_probe_modes:
    padded = torch.zeros(
        (probe.shape[0], n_probe_modes, *probe.shape[-2:]), dtype=get_default_complex_dtype()
    )
    padded[:, : probe.shape[1]] = probe
    probe = orthogonalize_initial_probe(padded, secondary_mode_energy=0.02)

# OPR modes.
if probe.shape[0] > n_opr_modes:
    probe = probe[:n_opr_modes]
elif probe.shape[0] < n_opr_modes:
    probe = add_additional_opr_probe_modes_to_probe(probe, n_opr_modes - probe.shape[0])

probe = torch.as_tensor(rescale_probe(probe, patterns), dtype=get_default_complex_dtype())
opr_weights = generate_initial_opr_mode_weights(len(positions_px), probe.shape[0], probe=probe)
print(f"probe: {tuple(probe.shape)} (n_opr, n_modes, h, w)")

fig, axes = plt.subplots(1, probe.shape[1], figsize=(3 * probe.shape[1], 3))
for i, ax in enumerate(np.atleast_1d(axes)):
    ax.imshow(np.abs(probe[0, i].numpy()), cmap="inferno")
    ax.set_title(f"mode {i}")
    ax.set_xticks([]), ax.set_yticks([])
plt.show()


#%% ---------------------------------------------------------------- initial object

object_shape = get_suggested_object_size(positions_px, probe.shape[-2:], extra=object_padding_px)
obj = torch.ones((1, *object_shape), dtype=get_default_complex_dtype())  # (n_slices, h, w)

# fracPy 0726 started flat; the 0728 variant pasted the prior object in. Uncomment to do that.
# if "object" in prior:
#     prior_obj = prior["object"].reshape((-1,) + prior["object"].shape[-2:])[0]
#     prior_obj = center_crop_or_pad(prior_obj, min(object_shape))
#     y0 = (object_shape[0] - prior_obj.shape[-2]) // 2
#     x0 = (object_shape[1] - prior_obj.shape[-1]) // 2
#     obj[0, y0 : y0 + prior_obj.shape[-2], x0 : x0 + prior_obj.shape[-1]] = torch.as_tensor(
#         prior_obj, dtype=get_default_complex_dtype()
#     )

print(f"object buffer: {tuple(obj.shape)}")

fig, axes = plt.subplots(1, 2, figsize=(8, 4))
axes[0].imshow(np.abs(obj[0].numpy()), cmap="inferno")
axes[0].set_title("initial object magnitude")
axes[1].imshow(np.angle(obj[0].numpy()), cmap="inferno")
axes[1].set_title("initial object phase")
for ax in axes:
    ax.set_aspect("equal")
plt.tight_layout()
plt.show()

#%% ---------------------------------------------------------------- options

options = api.LSQMLOptions()

# --- data / geometry ---
options.data_options.wavelength_m = wavelength_m
options.data_options.free_space_propagation_distance_m = np.inf if far_field else det_dist_m
# Measured patterns have DC at the center; the far-field forward model does not
# shift after the FFT, so the data must be pre-shifted. Near-field involves no
# Fraunhofer FFT, so it must not be shifted.
options.data_options.fft_shift = far_field
options.data_options.save_data_on_device = False   # True is faster if it fits in VRAM

# --- reconstructor ---
options.reconstructor_options.num_epochs = num_epochs
options.reconstructor_options.batch_size = batch_size
options.reconstructor_options.batching_mode = batching_mode
options.reconstructor_options.noise_model = noise_model
options.reconstructor_options.momentum_acceleration_gain = momentum_gain
options.reconstructor_options.default_device = device
options.reconstructor_options.default_dtype = dtype
options.reconstructor_options.random_seed = random_seed
options.reconstructor_options.rescale_probe_intensity_in_first_epoch = True

# --- object ---
options.object_options.optimizable = True
options.object_options.optimizer = api.Optimizers.SGD
options.object_options.step_size = 1.0
options.object_options.pixel_size_m = pixel_size_m
options.object_options.build_preconditioner_with_all_modes = update_object_with_higher_probe_modes
options.object_options.determine_position_origin_coords_by = (
    api.ObjectPosOriginCoordsMethods.SUPPORT
)
# fracPy object constraints (all off in the source script):
# options.object_options.l2_norm_constraint.enabled = True
# options.object_options.l2_norm_constraint.weight = 1e-3
# options.object_options.smoothness_constraint.enabled = True
# options.object_options.smoothness_constraint.alpha = 0.05

# --- probe ---
options.probe_options.optimizable = True
options.probe_options.optimizer = api.Optimizers.SGD
options.probe_options.step_size = 0.5
options.probe_options.optimization_plan = OptimizationPlan(start=probe_start)
options.probe_options.orthogonalize_incoherent_modes.enabled = n_probe_modes > 1
options.probe_options.orthogonalize_incoherent_modes.optimization_plan = OptimizationPlan(
    stride=orthogonalization_stride
)
options.probe_options.orthogonalize_incoherent_modes.method = api.OrthogonalizationMethods.SVD
options.probe_options.orthogonalize_opr_modes.enabled = n_opr_modes > 1
options.probe_options.power_constraint.enabled = False      # fracPy probePowerCorrectionSwitch
options.probe_options.center_constraint.enabled = center_probe  # fracPy comStabilizationSwitch

# --- probe positions (fracPy pcPIE) ---
if position_start is None:
    options.probe_position_options.optimizable = False
else:
    options.probe_position_options.optimizable = False
    options.probe_position_options.optimizer = api.Optimizers.SGD
    options.probe_position_options.step_size = 0.3
    options.probe_position_options.optimization_plan = OptimizationPlan(start=position_start)
    options.probe_position_options.constrain_position_mean = True
    options.probe_position_options.correction_options.correction_type = (
        api.PositionCorrectionTypes.GRADIENT
    )
    options.probe_position_options.correction_options.differentiation_method = (
        api.ImageGradientMethods.FOURIER_DIFFERENTIATION
    )
    options.probe_position_options.correction_options.update_magnitude_limit = (
        position_update_limit_px
    )
    options.probe_position_options.correction_options.clip_update_magnitude_by_mad = True
    options.probe_position_options.momentum_acceleration_gain = 0.5

# --- OPR mode weights (variable probe) ---
if n_opr_modes > 1 and opr_start is not None:
    options.opr_mode_weight_options.optimizable = True
    options.opr_mode_weight_options.optimize_eigenmode_weights = True
    options.opr_mode_weight_options.optimize_intensity_variation = optimize_intensity_variation
    options.opr_mode_weight_options.optimization_plan = OptimizationPlan(start=opr_start)
    options.opr_mode_weight_options.update_relaxation = 0.1
else:
    options.opr_mode_weight_options.optimizable = False

print(
    f"schedule: object 0-, probe {probe_start}-, OPR {opr_start}-, positions {position_start}-, "
    f"{num_epochs} epochs on {device}"
)


#%% ---------------------------------------------------------------- build task

task = PtychographyTask(
    options,
    diffraction_data=patterns,
    object_data=obj,
    probe_data=probe,
    probe_position_y_px=positions_px[:, 0],
    probe_position_x_px=positions_px[:, 1],
    opr_mode_weights_data=opr_weights,
)


#%% ---------------------------------------------------------------- run

# Re-derived here because use_simulated_data rewrites n_dp and batch_size after the
# cell that first set it; for a real scan this is the same path.
recon_dir = recon_parent_dir / scan / make_recon_dir_name(recon_dir_suffix)
save_initial_conditions(recon_dir)

# Like the beamline batch script, run in chunks of save_freq_iterations and drop a
# recon_Niter*.h5 snapshot after each one. State persists between task.run() calls,
# so this is identical to one long run — and the intermediate files let you pick up
# a reconstruction that was stopped early.
epochs_done = 0
while epochs_done < num_epochs:
    chunk = min(save_freq_iterations, num_epochs - epochs_done)
    task.run(chunk)
    epochs_done += chunk
    save_reconstruction(task, recon_dir, epochs_done)


#%% ---------------------------------------------------------------- inspect

recon_obj = task.get_data_to_cpu("object", as_numpy=True)[0]
recon_probe = task.get_data_to_cpu("probe", as_numpy=True)[0]
recon_pos = task.get_data_to_cpu("probe_positions", as_numpy=True)
loss_table = task.reconstructor.loss_tracker.table

fig, axes = plt.subplots(1, 3, figsize=(15, 7))
# axes[0].imshow(np.angle(recon_obj[380:480, 480:580]), cmap="gray")
axes[0].imshow(np.angle(recon_obj), cmap="gray")
axes[0].set_title("object phase")
axes[1].imshow(np.abs(recon_obj), cmap="gray")
axes[1].set_title("object magnitude")
axes[2].imshow(np.abs(recon_probe[0]), cmap="inferno")
axes[2].set_title("probe mode 0")
for ax in axes:
    ax.set_xticks([]), ax.set_yticks([])
plt.tight_layout()
plt.show()

plt.figure(figsize=(5, 3))
plt.semilogy(loss_table["epoch"], loss_table["loss"])
plt.xlabel("epoch"), plt.ylabel("loss")
plt.tight_layout()
plt.show()

if position_start is not None:
    plt.figure(figsize=(4, 4))
    plt.plot(positions_px[:, 1], positions_px[:, 0], ".", ms=3, label="initial")
    plt.plot(recon_pos[:, 1], recon_pos[:, 0], ".", ms=3, label="corrected")
    plt.gca().set_aspect("equal")
    plt.legend()
    plt.title("position correction")
    plt.show()


#%% ---------------------------------------------------------------- save

# The run loop above already wrote recon_Niter{save_freq_iterations}.h5 ...
# recon_Niter{num_epochs}.h5. This cell stands on its own: run it any time -- after a
# hand-issued task.run(n), or after interrupting the loop -- and it snapshots the
# current state under the number of epochs actually completed.
save_reconstruction(task, recon_dir)

# Extra, not part of the beamline layout: the full loss table including reg_loss.
task.reconstructor.loss_tracker.table.to_csv(recon_dir / "loss.csv", index=False)
print(f"results in {recon_dir}")

# %%
